# Generated by Django 2.2.13 on 2020-06-17 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_massmail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massmail',
            options={'verbose_name_plural': 'Mass Mail'},
        ),
        migrations.AddField(
            model_name='massmail',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
