# Generated by Django 3.2.12 on 2022-03-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('company_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('bidding_settings', models.SmallIntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')])),
                ('google_account_ads_id', models.CharField(max_length=200, verbose_name='Google Ads Account ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
