name: Bidnamic Pipeline
on: [push,pull_request]

jobs:
  bidnamic:
    runs-on: ubuntu-latest

    env:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: bidnamic
      DB_USER: bidnamic
      DB_PASSWORD: bidnamic
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
      ENVIRONMENT: prod
      USE_AWS: Yes
    services:
      postgres:
        image: postgres:14.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: bidnamic
          DB_PASSWORD: bidnamic
          POSTGRES_USER: bidnamic
          POSTGRES_PASSWORD: bidnamic
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: |
        pip3 install --user -r requirements.txt
        python3 manage.py migrate
        python3 manage.py test
