# Generated by Django 2.2.8 on 2019-12-07 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20191205_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo_6',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 7, 8, 34, 33, 822648)),
        ),
    ]
