# Generated by Django 2.2.8 on 2019-12-21 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20191207_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
