# Generated by Django 2.2.8 on 2019-12-05 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('photo', models.FileField(upload_to='photos/%Y/%m/%d/')),
                ('descriptiom', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 10, 59, 18, 623411))),
            ],
        ),
    ]
