# Generated by Django 2.2.8 on 2019-12-05 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20191205_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 21, 44, 649847)),
        ),
    ]
