# Generated by Django 2.2.8 on 2019-12-07 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20191205_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 8, 34, 33, 521836)),
        ),
    ]
