# Generated by Django 2.2.8 on 2019-12-21 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20191207_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
