# Generated by Django 3.2.11 on 2022-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220128_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update')], max_length=10)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=10)),
            ],
        ),
    ]
