# Generated by Django 2.2.8 on 2020-03-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField()),
                ('original_title', models.TextField(blank=True, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.FloatField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('num_imdb_ratings', models.IntegerField(blank=True, null=True)),
                ('rated', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('primary_genre', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('rotten_tomatoes_score', models.FloatField(blank=True, null=True)),
                ('metacritic_score', models.FloatField(blank=True, null=True)),
                ('production', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('omdb_metascore', models.FloatField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('boxoffice_earnings', models.TextField(blank=True, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
                ('dvd_release', models.DateTimeField(blank=True, db_column='DVD_release', null=True)),
                ('netflix_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amazon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hulu_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_seasons', models.IntegerField(blank=True, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('url_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('main_trailer', models.CharField(blank=True, max_length=2048, null=True)),
                ('reddit_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
    ]
