# Generated by Django 2.2.8 on 2020-03-17 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('movieid', models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movies')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Watches',
                'db_table': 'watches',
            },
        ),
        migrations.CreateModel(
            name='Usersettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('personalitytype', models.TextField(blank=True, db_column='personalityType', null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='dateOfBirth', null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, db_column='timeZone', max_length=255, null=True)),
                ('dateformat', models.CharField(blank=True, db_column='dateFormat', max_length=255, null=True)),
                ('timeformat', models.CharField(blank=True, db_column='timeFormat', max_length=255, null=True)),
                ('weekstarts', models.CharField(blank=True, db_column='weekStarts', max_length=255, null=True)),
                ('services', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
                'db_table': 'usersettings',
            },
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('movieid', models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movies')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': ' Reactions',
                'db_table': 'reactions',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('movieid', models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.CASCADE, to='movies.Movies')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='movies.Comments')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
            },
        ),
    ]
