version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./server/prod/django/Dockerfile
    volumes:
      - static:/static
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./server/nginx/Dockerfile
    restart: always
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
